package brands;

public enum PhoneBrand implements IBrand{
	ALCATEL,ALLVIEW,APPLE,CAT,DOOGEE,ENERGIZER,HONOR,HTC,HUAWEI,JUST5,LG,MAXCOM,MEIZU,MICROSOFT,MOTOROLA,MYPHONE,NOKIA,
	SAMSUNG,SONY,XIAOMI,ZTE
}
