package brands;

public enum VacuumCleanerBrand implements IBrand{
	BOSCH,BRAVISSIMO,DAEWOO,DYSON,ELECTROLUX,GORENJE,IROBOT,KARCHER,LG,MIELE,MYDOMO,NEO,PHILIPS,ROHNSON,
	ROWENTA,RUSSELL_HOBBS,SAMSUNG,SAPIR,SINGER,WHIRLPOOL,ZELMER,ZEPHYR
}
